

version: "3"
services:
  API:
    image: kiii-employee
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=kiii
